<table class='table'>
    <thead>
        <th scope='col'>trip</th>
        <th scope='col'>distance</th>
        <th scope='col'>measure interval</th>
        <th scope='col'>avg speed</th>
    </thead>
    <tbody>
        <?php foreach ($calculation as $item): ?>
            <tr>
                <td><?= $item['trip'] ?></td>
                <td><?= $item['distance'] ?></td>
                <td><?= $item['interval'] ?></td>
                <td><?= $item['avg_speed'] ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>